# Makes escape work without delay:
set -s escape-time 0
# Uses vi mode for selection:
set-window-option -g mode-keys vi
# Needed to make the keys work in WSL:
# bind-key -Tcopy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi 'y' send -X copy-selection
# Setup 'v' to begin selection, just like Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to yank (copy), just like Vim
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Move prefix to Ctrl A
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Start window and pane counts at 1
set -g base-index 1
setw -g pane-base-index 1

# Run in terminal to apply: 'tmux source ~/.tmux.conf'
